const ActionTypes = {
  PREPEND_SQUARE: 'PREPEND_SQUARE',
  ADD_SQUARE: 'ADD_SQUARE',
  ADD_SQUARES: 'ADD_SQUARES',
  SELECT_SQUARE: 'SELECT_SQUARE',
  BLAH: 'BLAH',
  SELECT_INCLUDED_SQUARES:'SELECT_INCLUDED_SQUARES',
  JOG_SQUARE_X: 'JOG_SQUARE_X',
  UNSELECT_ALL: 'UNSELECT_ALL',
  MOVE_SELECTED_SQUARES: 'MOVE_SELECTED_SQUARES'
};
export default ActionTypes;